### ISSUE TITLE
how to add body class to inner pages?

### ISSUE THREAD

**Issue by sarahball** [sarahball/upon-arrival#12]
I'd like to add an "inner" class or whatever to all inner pages @MikeRogers0 – how are you dynamically adding classes? 😄

**Comment by MikeRogers0** [comment]
@sarahball I'm adding them in `source/layouts/layout.erb` via `<body class="<%= yield_content(:from_location) %> <%= yield_content(:to_location) %>">` - Want them somewhere else?
