### ISSUE TITLE
URL structure

### ISSUE THREAD

**Issue by sarahball** [sarahball/upon-arrival#33]
Here's my wishlist! 🎁  🎅  🎄 

- [x] 1. Currently it's `/[going]-from-[from]/`. Would it be too much effort to make it `/[from]/[going]/`? That would be my ideal structure. If it's easier to keep it all on the same level, can we make it `/[from]-[going]/`?

- [ ] 2. I'd also like to change the word spacing. As it is, it's written like `buenos-aires` – I'd prefer `buenosaires`. So any place name that's multiple words would not have a dash in it.

- [x] 3. A few changes for names in the URLs, too! 👻

| Before             | After            |
| -------------- |:------------:|
| gb                    | uk                |
| us                    | usa               |
| ca                    | canada         |
| fr                      | france         |
| de                    | germany      |
| nl                     | netherlands |
| au                    | australia      |
| new-york-city | newyork      |
| kr                     | korea*         |
| ca                    | canada         |

*It's also "Korea, Republic of" on the search form – how to fix that?

**Comment by MikeRogers0** [comment]
1/3 -Sounds much better, I'll jump on by next call!
2 - I'm not a fan of combining words no blank spaces, it plays tricks on my dyslexia and I think it's not beneficial SEO wise.

"Korea, Republic of" - It's what comes out of the https://github.com/hexorx/countries gem, I agree it's not correct. I'll find a way to fix :)
