### ISSUE TITLE
index page questions

### ISSUE THREAD

**Issue by sarahball** [sarahball/upon-arrival#43]
Here are a few things I haven't been able to figure out own my own 🕵️ 

- The dropdowns on the index page – how to prevent them from making the page scroll when they are longer than the page?
- Loading the page with a random background image

**Comment by MikeRogers0** [comment]
I should have some time tomorrow to work on this 👍

**Comment by MikeRogers0** [comment]
@sarahball What is the status of this one?

IIRC, my todo on the homepage is currently:

- Preloading background
- Random background image

Sounds correct? :)

**Comment by MikeRogers0** [comment]
Both these are now in master, I'm going to close this now @sarahball :)
