### ISSUE TITLE
Criteria for top cities

### ISSUE THREAD

**Issue by sarahball** [sarahball/upon-arrival#5]
I think we should go with "[Trending Cities](https://nomadlist.com/trending-cities#sort=user_count)" on Nomadlist - aka the cities where the most people are. Obv. this varies throughout the year so it's not perfect. But I think since our goal is to help people in the places they go, this is a better metric than the overall Nomad Score.

Right now we've got: 
- London
- Chiang Mai
- Berlin
- Lisbon
- New York City
- Barcelona
- Bangkok
- Buenos Aires
- Amsterdam
- Budapest

**Comment by MikeRogers0** [comment]
@sarahball I think that's a good list to start with :)
