### ISSUE TITLE
"from" locations

### ISSUE THREAD

**Issue by sarahball** [sarahball/upon-arrival#9]
Somehow this failed to cross my mind until yesterday, but the "from" locations need to be different from the "going" locations.

To avoid getting new data for now, let's get the "from" data this way: 

|Original|Use data?|Becomes|
|---|---|---|
|London|yes|United Kingdom|
|Chiang Mai|no||
|Berlin|yes|Germany|
|Lisbon|no||
|New York City|yes|United States|
|Barcelona|yes|Spain|
|Bangkok|no||
|Buenos Aires|no||
|Amsterdam|yes|The Netherlands|
|Budapest|no||

I'd like to add these "from" countries, just because anecdotally I meet tons of travelers from these places. But we can skip for the MVP if it's too much:
- Canada
- France
- Australia
- South Korea

**Comment by MikeRogers0** [comment]
That makes loads more sense, so from will always be the country but to is the city?
